---
version: '3'
services:

  # database
  db-0:
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c wal_level=logical
    container_name: db-0
    environment:
      - POSTGRES_DB=platform
      - POSTGRES_PASSWORD=secret
    expose:
      - "5432"
    image: postgres:14.3-alpine
    ports:
      - "5432:5432"
    volumes:
      - db-0:/var/lib/postgresql/data 

  # platform
  platform:
    build:
      dockerfile: Dockerfile
    container_name: platform
    depends_on:
      - db-0
    links:
      - "db-0:db"
    ports:
      - "7349:7349"
      - "7350:7350"
      - "7351:7351"
    restart: unless-stopped

volumes:
  db-0: 