---
version: '3'
services:
  # platform
  platform:
    build:
      dockerfile: Dockerfile
    container_name: platform
    ports:
      - "7349:7349"
      - "7350:7350"
      - "7351:7351"
    restart: unless-stopped

volumes:
  db-0: 